name: repository dispatch test

on:
  repository_dispatch:
    types: [on-demand-test]

jobs:
  build1:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{ github.event.client_payload.test }}"

  build2:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "test2"

  build3:
    runs-on: ubuntu-latest
    needs: build2
    steps:
      - run: |
          echo "test3"