name: workflow dispatch test title

on:
  workflow_dispatch:

jobs:
  build1:
    uses: ./.github/workflows/workflow_call.yaml
    with:
      input1: "aaa"
      input2: "bbb"
    # runs-on: ubuntu-latest
    # # outputs:
    # #   output1: ${{ steps.step1.outputs.test }}
    # # steps:
    # #   - id: step1
    # #     run: |
    # #       echo "${{ github.ref_name }}"
    # #       echo "${{ github.ref_type }}"
    # #       echo "test=test1" >> "$GITHUB_OUTPUT"

  # build2:
  #   runs-on: ubuntu-latest
  #   outputs:
  #     output1: ${{ steps.step2.outputs.test }}
  #   needs: build1
  #   steps:
  #     - id: step2
  #       run: |
  #         echo "test=${{needs.build1.outputs.output1}}" >> "$GITHUB_OUTPUT"

  # build3:
  #   runs-on: ubuntu-latest
  #   needs: build2
  #   steps:
  #     - run: |
  #         echo "${{needs.build2.outputs.output1}}"
  
