name: workflow call test

on:
  workflow_call:
    inputs:
      input1:
        required: true
        type: string
      input2:
        required: true
        type: string

jobs:
  build1:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "::add-mask::${{ inputs.input1 }}"
          echo "${{ github.event.action }}"
          echo "${{ github.action }}"
          echo "${{ github.event.inputs.input1 }}"
          echo "${{ github.event.inputs.input2 }}"
          echo "${{ inputs.input1 }}"
          echo "${{ inputs.input2 }}"
          echo "${{ secrets.NORMAL }}"

